site_name: My Personal documentation
repo_name:
repo_url:
edit_uri:

nav:
  - Home:
      Welcome: index.md
  - Kubernetes: kubernetes.md
  - Aws:
      - ACM: aws/aws.md
  - Github:
      - Workflows: github/github.md
      - runner: github/gh_runner.md
  - Gitlab:
      - Runner: gitlab/gl_runner.md


plugins:
  - search
theme:
  name: material
  language: en
#  favicon: assets/images/aws_load_balancer_icon.svg
  palette:
    primary: indigo
    accent: indigomk
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
#  custom_dir: docs/theme_overrides
#Extensions
markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
extra_css:
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css
extra_javascript:
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js
