apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: gha-runner-scale-set
    releaseName: ado10-runner-set
    namespace: core-arc-systems
    valuesInline:
      githubConfigUrl: https://github.com/snteks
      githubConfigSecret:
        github_token: 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
      controllerServiceAccount:
         namespace: core-arc-systems
         name: gha-runner-scale-set-controller-gha-rs-controller
