name: Install ArgoCD to k8s cluster
on:
  push:
    branches:
      - main

jobs:
  Install ArgoCD:
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Kustomize
        shell: bash
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv ./kustomize /usr/local/bin/kustomize

      - name: connect with eks cluster
        shell: bash
        run: |
            aws eks update-kubeconfig --name ${{ inputs.eks_cluster }} --region ${{ inputs.aws_region }}
            aws sts get-caller-identity
            aws eks get-token --region ${{ inputs.aws_region }} --cluster-name ${{ inputs.eks_cluster }}

      - name: Deploy kustomization
        shell: bash
        run: |
          cd cheatsheet/kustomize/argoCD
          kustomize build . | kubectl apply -f -

